window.DATA_SENTENCES = [

// Chủ đề Gia đình (ID: 1)
{ id:'s1',category:'1',english:'I live with my family.',vietnamese:'Tôi sống cùng gia đình.'},
{ id:'s2',category:'1',english:'I have two kids.',vietnamese:'Tôi có hai đứa con.'},
{ id:'s3',category:'1',english:'My parents live nearby.',vietnamese:'Bố mẹ tôi sống gần đây.'},
{ id:'s4',category:'1',english:'I am married.',vietnamese:'Tôi đã kết hôn.'},
{ id:'s5',category:'1',english:'She is single.',vietnamese:'Cô ấy độc thân.'},
{ id:'s6',category:'1',english:'We are a close family.',vietnamese:'Chúng tôi là gia đình thân thiết.'},
{ id:'s7',category:'1',english:'I take care of my parents.',vietnamese:'Tôi chăm sóc bố mẹ.'},
{ id:'s8',category:'1',english:'My kids are at school.',vietnamese:'Con tôi đang đi học.'},
{ id:'s9',category:'1',english:'I visit my parents every week.',vietnamese:'Tôi thăm bố mẹ mỗi tuần.'},
{ id:'s10',category:'1',english:'We spend time together on weekends.',vietnamese:'Cuối tuần chúng tôi dành thời gian bên nhau.'},
{ id:'s11',category:'1',english:'My wife is at home.',vietnamese:'Vợ tôi đang ở nhà.'},
{ id:'s12',category:'1',english:'My husband works a lot.',vietnamese:'Chồng tôi làm việc nhiều.'},
{ id:'s13',category:'1',english:'My baby is sleeping.',vietnamese:'Em bé đang ngủ.'},
{ id:'s14',category:'1',english:'I help my kids with homework.',vietnamese:'Tôi giúp con làm bài.'},
{ id:'s15',category:'1',english:'We stay at home tonight.',vietnamese:'Tối nay chúng tôi ở nhà.'},
{ id:'s16',category:'1',english:'I love my family.',vietnamese:'Tôi yêu gia đình tôi.'},
{ id:'s17',category:'1',english:'We support each other.',vietnamese:'Chúng tôi hỗ trợ lẫn nhau.'},
{ id:'s18',category:'1',english:'My relatives are coming.',vietnamese:'Họ hàng tôi sắp tới.'},
{ id:'s19',category:'1',english:'We grow up together.',vietnamese:'Chúng tôi lớn lên cùng nhau.'},
{ id:'s20',category:'1',english:'I stay with my kids.',vietnamese:'Tôi ở với con.'},
{ id:'s21',category:'1',english:'I take my kids to school.',vietnamese:'Tôi đưa con đi học.'},
{ id:'s22',category:'1',english:'We eat dinner together.',vietnamese:'Chúng tôi ăn tối cùng nhau.'},
{ id:'s23',category:'1',english:'My family helps me a lot.',vietnamese:'Gia đình giúp tôi rất nhiều.'},
{ id:'s24',category:'1',english:'I visit my relatives.',vietnamese:'Tôi thăm họ hàng.'},
{ id:'s25',category:'1',english:'We live in the same house.',vietnamese:'Chúng tôi sống chung một nhà.'},
{ id:'s26',category:'1',english:'I spend time with my parents.',vietnamese:'Tôi dành thời gian với bố mẹ.'},
{ id:'s27',category:'1',english:'My sister lives nearby.',vietnamese:'Chị tôi sống gần đây.'},
{ id:'s28',category:'1',english:'My brother works abroad.',vietnamese:'Anh tôi làm việc ở nước ngoài.'},
{ id:'s29',category:'1',english:'We take care of each other.',vietnamese:'Chúng tôi chăm sóc nhau.'},
{ id:'s30',category:'1',english:'Family is very important to me.',vietnamese:'Gia đình rất quan trọng với tôi.'},

// Chủ đề Bản thân (ID: 2)
{ id:'s1',category:'2',english:'My name is Tung.',vietnamese:'Tên tôi là Tùng.'},
{ id:'s2',category:'2',english:'I am 30 years old.',vietnamese:'Tôi 30 tuổi.'},
{ id:'s3',category:'2',english:'I am from Vietnam.',vietnamese:'Tôi đến từ Việt Nam.'},
{ id:'s4',category:'2',english:'I live in the city.',vietnamese:'Tôi sống ở thành phố.'},
{ id:'s5',category:'2',english:'I work full-time.',vietnamese:'Tôi làm toàn thời gian.'},
{ id:'s6',category:'2',english:'My job is busy.',vietnamese:'Công việc tôi bận.'},
{ id:'s7',category:'2',english:'I like learning English.',vietnamese:'Tôi thích học tiếng Anh.'},
{ id:'s8',category:'2',english:'I speak English a little.',vietnamese:'Tôi nói tiếng Anh một chút.'},
{ id:'s9',category:'2',english:'I am free today.',vietnamese:'Hôm nay tôi rảnh.'},
{ id:'s10',category:'2',english:'I am busy now.',vietnamese:'Bây giờ tôi bận.'},
{ id:'s11',category:'2',english:'I am tired.',vietnamese:'Tôi mệt.'},
{ id:'s12',category:'2',english:'I am happy today.',vietnamese:'Hôm nay tôi vui.'},
{ id:'s13',category:'2',english:'I am interested in technology.',vietnamese:'Tôi quan tâm đến công nghệ.'},
{ id:'s14',category:'2',english:'I learn something new every day.',vietnamese:'Tôi học cái mới mỗi ngày.'},
{ id:'s15',category:'2',english:'I meet my friends often.',vietnamese:'Tôi thường gặp bạn.'},
{ id:'s16',category:'2',english:'I have many friends.',vietnamese:'Tôi có nhiều bạn.'},
{ id:'s17',category:'2',english:'I study English at home.',vietnamese:'Tôi học tiếng Anh ở nhà.'},
{ id:'s18',category:'2',english:'I am here now.',vietnamese:'Tôi đang ở đây.'},
{ id:'s19',category:'2',english:'I work today.',vietnamese:'Hôm nay tôi đi làm.'},
{ id:'s20',category:'2',english:'I am not free tonight.',vietnamese:'Tối nay tôi không rảnh.'},
{ id:'s21',category:'2',english:'I feel a bit sad.',vietnamese:'Tôi hơi buồn.'},
{ id:'s22',category:'2',english:'I like this place.',vietnamese:'Tôi thích chỗ này.'},
{ id:'s23',category:'2',english:'I learn English online.',vietnamese:'Tôi học tiếng Anh online.'},
{ id:'s24',category:'2',english:'I meet people every day.',vietnamese:'Tôi gặp người mỗi ngày.'},
{ id:'s25',category:'2',english:'I am busy this week.',vietnamese:'Tuần này tôi bận.'},
{ id:'s26',category:'2',english:'I am free tomorrow.',vietnamese:'Ngày mai tôi rảnh.'},
{ id:'s27',category:'2',english:'I am here to learn.',vietnamese:'Tôi ở đây để học.'},
{ id:'s28',category:'2',english:'I like my job.',vietnamese:'Tôi thích công việc của mình.'},
{ id:'s29',category:'2',english:'I am happy with my life.',vietnamese:'Tôi hài lòng với cuộc sống.'},
{ id:'s30',category:'2',english:'I am at home now.',vietnamese:'Bây giờ tôi đang ở nhà.'},

// Chủ đề Số đếm & Thời gian (ID: 3)
{ id:'s1',category:'3',english:'What time is it now?',vietnamese:'Bây giờ là mấy giờ?'},
{ id:'s2',category:'3',english:'It is morning now.',vietnamese:'Bây giờ là buổi sáng.'},
{ id:'s3',category:'3',english:'I work in the morning.',vietnamese:'Tôi làm việc buổi sáng.'},
{ id:'s4',category:'3',english:'I am busy this afternoon.',vietnamese:'Chiều nay tôi bận.'},
{ id:'s5',category:'3',english:'I will call you later.',vietnamese:'Tôi sẽ gọi bạn sau.'},
{ id:'s6',category:'3',english:'I am free tomorrow.',vietnamese:'Ngày mai tôi rảnh.'},
{ id:'s7',category:'3',english:'I was busy yesterday.',vietnamese:'Hôm qua tôi bận.'},
{ id:'s8',category:'3',english:'I am busy right now.',vietnamese:'Bây giờ tôi bận.'},
{ id:'s9',category:'3',english:'Please come on time.',vietnamese:'Đến đúng giờ nhé.'},
{ id:'s10',category:'3',english:'I am late again.',vietnamese:'Tôi lại trễ.'},
{ id:'s11',category:'3',english:'I always wake up early.',vietnamese:'Tôi luôn dậy sớm.'},
{ id:'s12',category:'3',english:'I usually work all day.',vietnamese:'Tôi thường làm cả ngày.'},
{ id:'s13',category:'3',english:'Sometimes I work at night.',vietnamese:'Thỉnh thoảng tôi làm ban đêm.'},
{ id:'s14',category:'3',english:'I never forget the time.',vietnamese:'Tôi không bao giờ quên giờ.'},
{ id:'s15',category:'3',english:'We meet every week.',vietnamese:'Chúng tôi gặp nhau mỗi tuần.'},
{ id:'s16',category:'3',english:'It takes one hour.',vietnamese:'Mất một giờ.'},
{ id:'s17',category:'3',english:'Please wait a minute.',vietnamese:'Đợi một phút.'},
{ id:'s18',category:'3',english:'I am free this weekend.',vietnamese:'Cuối tuần này tôi rảnh.'},
{ id:'s19',category:'3',english:'I will be there soon.',vietnamese:'Tôi sẽ tới sớm.'},
{ id:'s20',category:'3',english:'It is too late now.',vietnamese:'Bây giờ trễ quá.'},
{ id:'s21',category:'3',english:'I have no time today.',vietnamese:'Hôm nay tôi không có thời gian.'},
{ id:'s22',category:'3',english:'Let us start now.',vietnamese:'Bắt đầu bây giờ nhé.'},
{ id:'s23',category:'3',english:'We work every day.',vietnamese:'Chúng tôi làm việc mỗi ngày.'},
{ id:'s24',category:'3',english:'I stay at home all day.',vietnamese:'Tôi ở nhà cả ngày.'},
{ id:'s25',category:'3',english:'I am early today.',vietnamese:'Hôm nay tôi đến sớm.'},
{ id:'s26',category:'3',english:'We are late for work.',vietnamese:'Chúng tôi trễ giờ làm.'},
{ id:'s27',category:'3',english:'I am busy this month.',vietnamese:'Tháng này tôi bận.'},
{ id:'s28',category:'3',english:'I have time now.',vietnamese:'Bây giờ tôi có thời gian.'},
{ id:'s29',category:'3',english:'We meet on the weekend.',vietnamese:'Chúng tôi gặp nhau cuối tuần.'},
{ id:'s30',category:'3',english:'I am free at night.',vietnamese:'Buổi tối tôi rảnh.'},

// Chủ đề Màu sắc & Hình dạng (ID: 4)
{ id:'s401',category:'4',english:'The car is red.',vietnamese:'Chiếc xe màu đỏ.'},
{ id:'s402',category:'4',english:'This room is very clean.',vietnamese:'Phòng này rất sạch.'},
{ id:'s403',category:'4',english:'That bag is too heavy.',vietnamese:'Cái túi đó quá nặng.'},
{ id:'s404',category:'4',english:'My house is near here.',vietnamese:'Nhà tôi ở gần đây.'},
{ id:'s405',category:'4',english:'The food is hot.',vietnamese:'Đồ ăn nóng.'},
{ id:'s406',category:'4',english:'The water is cold.',vietnamese:'Nước lạnh.'},
{ id:'s407',category:'4',english:'This shirt is too small.',vietnamese:'Cái áo này quá nhỏ.'},
{ id:'s408',category:'4',english:'That table is very big.',vietnamese:'Cái bàn kia rất to.'},
{ id:'s409',category:'4',english:'This phone is new.',vietnamese:'Điện thoại này mới.'},
{ id:'s410',category:'4',english:'My shoes are old.',vietnamese:'Giày tôi cũ rồi.'},
{ id:'s411',category:'4',english:'The bus is fast.',vietnamese:'Xe buýt chạy nhanh.'},
{ id:'s412',category:'4',english:'This road is long.',vietnamese:'Con đường này dài.'},
{ id:'s413',category:'4',english:'The box is empty.',vietnamese:'Cái hộp trống.'},
{ id:'s414',category:'4',english:'The glass is full.',vietnamese:'Cái ly đầy.'},
{ id:'s415',category:'4',english:'My house is far from here.',vietnamese:'Nhà tôi xa chỗ này.'},
{ id:'s416',category:'4',english:'These two bags are the same.',vietnamese:'Hai cái túi này giống nhau.'},
{ id:'s417',category:'4',english:'This color is different.',vietnamese:'Màu này khác.'},
{ id:'s418',category:'4',english:'The pillow is soft.',vietnamese:'Cái gối mềm.'},
{ id:'s419',category:'4',english:'The chair is hard.',vietnamese:'Cái ghế cứng.'},
{ id:'s420',category:'4',english:'The room is dark.',vietnamese:'Phòng tối.'},
{ id:'s421',category:'4',english:'The screen is too bright.',vietnamese:'Màn hình quá sáng.'},
{ id:'s422',category:'4',english:'The water is dirty.',vietnamese:'Nước bẩn.'},
{ id:'s423',category:'4',english:'The street is busy.',vietnamese:'Con đường đông.'},
{ id:'s424',category:'4',english:'The store is near my house.',vietnamese:'Cửa hàng gần nhà tôi.'},
{ id:'s425',category:'4',english:'The bag is light.',vietnamese:'Cái túi nhẹ.'},
{ id:'s426',category:'4',english:'The car is slow.',vietnamese:'Chiếc xe chạy chậm.'},
{ id:'s427',category:'4',english:'The floor is clean.',vietnamese:'Sàn nhà sạch.'},
{ id:'s428',category:'4',english:'The water is warm.',vietnamese:'Nước ấm.'},
{ id:'s429',category:'4',english:'My house is very quiet.',vietnamese:'Nhà tôi rất yên tĩnh.'},
{ id:'s430',category:'4',english:'This place is nice.',vietnamese:'Chỗ này đẹp.'},

// Chủ đề Đồ vật xung quanh (ID: 5)
{ id:'s501',category:'5',english:'My phone is on the table.',vietnamese:'Điện thoại tôi ở trên bàn.'},
{ id:'s502',category:'5',english:'The keys are in my bag.',vietnamese:'Chìa khóa ở trong túi tôi.'},
{ id:'s503',category:'5',english:'Turn off the light, please.',vietnamese:'Tắt đèn giúp tôi.'},
{ id:'s504',category:'5',english:'Open the window, please.',vietnamese:'Mở cửa sổ giúp tôi.'},
{ id:'s505',category:'5',english:'Close the door.',vietnamese:'Đóng cửa lại.'},
{ id:'s506',category:'5',english:'My laptop is very slow.',vietnamese:'Laptop tôi rất chậm.'},
{ id:'s507',category:'5',english:'Where is the remote?',vietnamese:'Cái điều khiển đâu rồi?'},
{ id:'s508',category:'5',english:'My shoes are under the bed.',vietnamese:'Giày tôi ở dưới giường.'},
{ id:'s509',category:'5',english:'Put the book on the shelf.',vietnamese:'Để sách lên kệ.'},
{ id:'s510',category:'5',english:'The trash is full.',vietnamese:'Thùng rác đầy rồi.'},
{ id:'s511',category:'5',english:'I need a clean towel.',vietnamese:'Tôi cần cái khăn sạch.'},
{ id:'s512',category:'5',english:'The clock is broken.',vietnamese:'Cái đồng hồ hỏng rồi.'},
{ id:'s513',category:'5',english:'Please wash the cup.',vietnamese:'Rửa cái ly giúp tôi.'},
{ id:'s514',category:'5',english:'The mirror is dirty.',vietnamese:'Cái gương bẩn.'},
{ id:'s515',category:'5',english:'My bag is very heavy.',vietnamese:'Túi tôi rất nặng.'},
{ id:'s516',category:'5',english:'Put the clothes in the drawer.',vietnamese:'Để quần áo vào ngăn kéo.'},
{ id:'s517',category:'5',english:'The fan is too noisy.',vietnamese:'Cái quạt ồn quá.'},
{ id:'s518',category:'5',english:'The TV is on.',vietnamese:'Tivi đang bật.'},
{ id:'s519',category:'5',english:'Turn off the TV.',vietnamese:'Tắt tivi.'},
{ id:'s520',category:'5',english:'I lost my key.',vietnamese:'Tôi mất chìa khóa rồi.'},
{ id:'s521',category:'5',english:'The bottle is empty.',vietnamese:'Cái chai trống.'},
{ id:'s522',category:'5',english:'The box is under the table.',vietnamese:'Cái hộp ở dưới bàn.'},
{ id:'s523',category:'5',english:'Please throw away the trash.',vietnamese:'Làm ơn vứt rác đi.'},
{ id:'s524',category:'5',english:'I need a pen and paper.',vietnamese:'Tôi cần bút và giấy.'},
{ id:'s525',category:'5',english:'The shelf is full of books.',vietnamese:'Kệ đầy sách.'},
{ id:'s526',category:'5',english:'My clothes are in the bag.',vietnamese:'Quần áo ở trong túi.'},
{ id:'s527',category:'5',english:'The cup is hot.',vietnamese:'Cái ly nóng.'},
{ id:'s528',category:'5',english:'The floor is wet.',vietnamese:'Sàn nhà ướt.'},
{ id:'s529',category:'5',english:'The chair is broken.',vietnamese:'Cái ghế bị hỏng.'},
{ id:'s530',category:'5',english:'Put the box on the table.',vietnamese:'Để cái hộp lên bàn.'},

// Chủ đề Nhà cửa (ID: 6)
{ id:'s601',category:'6',english:'My house is small but clean.',vietnamese:'Nhà tôi nhỏ nhưng sạch.'},
{ id:'s602',category:'6',english:'The bedroom is very quiet.',vietnamese:'Phòng ngủ rất yên tĩnh.'},
{ id:'s603',category:'6',english:'The kitchen is too hot.',vietnamese:'Nhà bếp nóng quá.'},
{ id:'s604',category:'6',english:'The bathroom is wet.',vietnamese:'Phòng tắm ướt.'},
{ id:'s605',category:'6',english:'Turn on the air conditioner.',vietnamese:'Bật máy lạnh lên.'},
{ id:'s606',category:'6',english:'Please turn off the fan.',vietnamese:'Tắt quạt giúp tôi.'},
{ id:'s607',category:'6',english:'The fridge is empty.',vietnamese:'Tủ lạnh trống.'},
{ id:'s608',category:'6',english:'I need to wash my clothes.',vietnamese:'Tôi cần giặt đồ.'},
{ id:'s609',category:'6',english:'The washing machine is broken.',vietnamese:'Máy giặt hỏng rồi.'},
{ id:'s610',category:'6',english:'The light is too bright.',vietnamese:'Đèn sáng quá.'},
{ id:'s611',category:'6',english:'The plug is loose.',vietnamese:'Ổ cắm lỏng.'},
{ id:'s612',category:'6',english:'The shower is not working.',vietnamese:'Vòi sen không hoạt động.'},
{ id:'s613',category:'6',english:'Close the curtain, please.',vietnamese:'Kéo rèm lại giúp tôi.'},
{ id:'s614',category:'6',english:'The floor is dirty.',vietnamese:'Sàn bẩn.'},
{ id:'s615',category:'6',english:'The ceiling is leaking.',vietnamese:'Trần nhà bị dột.'},
{ id:'s616',category:'6',english:'The balcony is very windy.',vietnamese:'Ban công gió mạnh.'},
{ id:'s617',category:'6',english:'My room has a big window.',vietnamese:'Phòng tôi có cửa sổ lớn.'},
{ id:'s618',category:'6',english:'Please clean the yard.',vietnamese:'Dọn sân giúp tôi.'},
{ id:'s619',category:'6',english:'The garage is full.',vietnamese:'Nhà xe đầy.'},
{ id:'s620',category:'6',english:'The sofa is very comfortable.',vietnamese:'Ghế sofa rất êm.'},
{ id:'s621',category:'6',english:'I left my phone on the bed.',vietnamese:'Tôi để điện thoại trên giường.'},
{ id:'s622',category:'6',english:'The toilet is blocked.',vietnamese:'Nhà vệ sinh bị nghẹt.'},
{ id:'s623',category:'6',english:'There is water on the floor.',vietnamese:'Có nước trên sàn.'},
{ id:'s624',category:'6',english:'The lamp is too dark.',vietnamese:'Đèn tối quá.'},
{ id:'s625',category:'6',english:'Please fix the switch.',vietnamese:'Sửa công tắc giúp tôi.'},
{ id:'s626',category:'6',english:'The blanket is very warm.',vietnamese:'Cái chăn rất ấm.'},
{ id:'s627',category:'6',english:'The pillow is too hard.',vietnamese:'Cái gối cứng quá.'},
{ id:'s628',category:'6',english:'The sink is full of dishes.',vietnamese:'Bồn rửa đầy chén.'},
{ id:'s629',category:'6',english:'The door is locked.',vietnamese:'Cửa bị khóa.'},
{ id:'s630',category:'6',english:'Open the window for fresh air.',vietnamese:'Mở cửa sổ cho thoáng.'},

// Chủ đề Thức ăn & Đồ uống (ID: 7)
{ id:'s701',category:'7',english:'I am very hungry.',vietnamese:'Tôi rất đói.'},
{ id:'s702',category:'7',english:'Let us order some food.',vietnamese:'Gọi đồ ăn nhé.'},
{ id:'s703',category:'7',english:'This soup is very hot.',vietnamese:'Canh này rất nóng.'},
{ id:'s704',category:'7',english:'The chicken is delicious.',vietnamese:'Gà rất ngon.'},
{ id:'s705',category:'7',english:'I like spicy food.',vietnamese:'Tôi thích ăn cay.'},
{ id:'s706',category:'7',english:'The coffee is too bitter.',vietnamese:'Cà phê đắng quá.'},
{ id:'s707',category:'7',english:'Can I have some water?',vietnamese:'Cho tôi xin ít nước.'},
{ id:'s708',category:'7',english:'I want a cup of tea.',vietnamese:'Tôi muốn một ly trà.'},
{ id:'s709',category:'7',english:'The milk is cold.',vietnamese:'Sữa lạnh.'},
{ id:'s710',category:'7',english:'The salad is fresh.',vietnamese:'Salad tươi.'},
{ id:'s711',category:'7',english:'I eat rice every day.',vietnamese:'Tôi ăn cơm mỗi ngày.'},
{ id:'s712',category:'7',english:'This fish is very tasty.',vietnamese:'Cá này rất ngon.'},
{ id:'s713',category:'7',english:'The juice is sweet.',vietnamese:'Nước ép ngọt.'},
{ id:'s714',category:'7',english:'The soup is too salty.',vietnamese:'Canh mặn quá.'},
{ id:'s715',category:'7',english:'I am full now.',vietnamese:'Giờ tôi no rồi.'},
{ id:'s716',category:'7',english:'Let us have lunch.',vietnamese:'Ăn trưa nhé.'},
{ id:'s717',category:'7',english:'What do you want to eat?',vietnamese:'Bạn muốn ăn gì?'},
{ id:'s718',category:'7',english:'I want noodles.',vietnamese:'Tôi muốn ăn mì.'},
{ id:'s719',category:'7',english:'Please bring the menu.',vietnamese:'Cho xem menu.'},
{ id:'s720',category:'7',english:'Can I order now?',vietnamese:'Tôi gọi món được chưa?'},
{ id:'s721',category:'7',english:'The food is too oily.',vietnamese:'Đồ ăn nhiều dầu quá.'},
{ id:'s722',category:'7',english:'The beef is very soft.',vietnamese:'Thịt bò rất mềm.'},
{ id:'s723',category:'7',english:'I do not eat pork.',vietnamese:'Tôi không ăn thịt heo.'},
{ id:'s724',category:'7',english:'The fruit is very fresh.',vietnamese:'Trái cây rất tươi.'},
{ id:'s725',category:'7',english:'I need a clean spoon.',vietnamese:'Tôi cần cái muỗng sạch.'},
{ id:'s726',category:'7',english:'The tea is too hot.',vietnamese:'Trà nóng quá.'},
{ id:'s727',category:'7',english:'Can I have some more rice?',vietnamese:'Cho tôi thêm cơm.'},
{ id:'s728',category:'7',english:'The food is ready.',vietnamese:'Đồ ăn xong rồi.'},
{ id:'s729',category:'7',english:'Let us share the food.',vietnamese:'Chia đồ ăn ra nhé.'},
{ id:'s730',category:'7',english:'I eat at home today.',vietnamese:'Hôm nay tôi ăn ở nhà.'},

// Chủ đề Mua sắm (ID: 8)
{ id:'s801',category:'8',english:'How much is this?',vietnamese:'Cái này giá bao nhiêu?'},
{ id:'s802',category:'8',english:'This is too expensive.',vietnamese:'Cái này đắt quá.'},
{ id:'s803',category:'8',english:'Do you have a cheaper one?',vietnamese:'Có cái rẻ hơn không?'},
{ id:'s804',category:'8',english:'Can I get a discount?',vietnamese:'Tôi được giảm giá không?'},
{ id:'s805',category:'8',english:'I want to buy this.',vietnamese:'Tôi muốn mua cái này.'},
{ id:'s806',category:'8',english:'Can I try this on?',vietnamese:'Tôi thử cái này được không?'},
{ id:'s807',category:'8',english:'This size does not fit me.',vietnamese:'Size này không vừa.'},
{ id:'s808',category:'8',english:'Do you take cash or card?',vietnamese:'Nhận tiền mặt hay thẻ?'},
{ id:'s809',category:'8',english:'Please give me the receipt.',vietnamese:'Cho tôi hóa đơn.'},
{ id:'s810',category:'8',english:'Can I return this?',vietnamese:'Tôi trả lại được không?'},
{ id:'s811',category:'8',english:'I want a refund.',vietnamese:'Tôi muốn hoàn tiền.'},
{ id:'s812',category:'8',english:'This product is broken.',vietnamese:'Sản phẩm này bị hỏng.'},
{ id:'s813',category:'8',english:'Is this on sale?',vietnamese:'Cái này đang giảm giá không?'},
{ id:'s814',category:'8',english:'I bought this online.',vietnamese:'Tôi mua cái này online.'},
{ id:'s815',category:'8',english:'When will it be delivered?',vietnamese:'Khi nào giao hàng?'},
{ id:'s816',category:'8',english:'The quality is very good.',vietnamese:'Chất lượng rất tốt.'},
{ id:'s817',category:'8',english:'This color is nice.',vietnamese:'Màu này đẹp.'},
{ id:'s818',category:'8',english:'I am looking for a gift.',vietnamese:'Tôi đang tìm quà.'},
{ id:'s819',category:'8',english:'Do you have this in blue?',vietnamese:'Có màu xanh không?'},
{ id:'s820',category:'8',english:'Please pack this for me.',vietnamese:'Gói cái này giúp tôi.'},
{ id:'s821',category:'8',english:'I will pay by card.',vietnamese:'Tôi trả bằng thẻ.'},
{ id:'s822',category:'8',english:'Here is your change.',vietnamese:'Đây là tiền thối của bạn.'},
{ id:'s823',category:'8',english:'The store is closed.',vietnamese:'Cửa hàng đóng cửa rồi.'},
{ id:'s824',category:'8',english:'The shop opens at nine.',vietnamese:'Cửa hàng mở lúc 9 giờ.'},
{ id:'s825',category:'8',english:'This brand is popular.',vietnamese:'Thương hiệu này phổ biến.'},
{ id:'s826',category:'8',english:'I am just looking.',vietnamese:'Tôi chỉ xem thôi.'},
{ id:'s827',category:'8',english:'Please keep the bag.',vietnamese:'Giữ túi nhé.'},
{ id:'s828',category:'8',english:'This is a good deal.',vietnamese:'Món này hời.'},
{ id:'s829',category:'8',english:'I need to buy groceries.',vietnamese:'Tôi cần mua đồ ăn.'},
{ id:'s830',category:'8',english:'The price went up.',vietnamese:'Giá tăng rồi.'},

// Chủ đề Giao thông (ID: 9)
{ id:'s901',category:'9',english:'How do I get to the station?',vietnamese:'Đi đến nhà ga như thế nào?'},
{ id:'s902',category:'9',english:'Turn left at the next street.',vietnamese:'Rẽ trái ở con phố kế tiếp.'},
{ id:'s903',category:'9',english:'Go straight and then turn right.',vietnamese:'Đi thẳng rồi rẽ phải.'},
{ id:'s904',category:'9',english:'The bus stop is near here.',vietnamese:'Trạm xe buýt gần đây.'},
{ id:'s905',category:'9',english:'Is the airport far from here?',vietnamese:'Sân bay xa đây không?'},
{ id:'s906',category:'9',english:'I take the bus to work.',vietnamese:'Tôi đi làm bằng xe buýt.'},
{ id:'s907',category:'9',english:'Call me a taxi, please.',vietnamese:'Gọi taxi giúp tôi.'},
{ id:'s908',category:'9',english:'The train is late.',vietnamese:'Tàu trễ.'},
{ id:'s909',category:'9',english:'Where can I buy a ticket?',vietnamese:'Mua vé ở đâu?'},
{ id:'s910',category:'9',english:'The traffic is very bad today.',vietnamese:'Hôm nay kẹt xe quá.'},
{ id:'s911',category:'9',english:'Please slow down.',vietnamese:'Chạy chậm lại.'},
{ id:'s912',category:'9',english:'We arrived on time.',vietnamese:'Chúng tôi đến đúng giờ.'},
{ id:'s913',category:'9',english:'The bus leaves at eight.',vietnamese:'Xe buýt chạy lúc 8 giờ.'},
{ id:'s914',category:'9',english:'Cross the road carefully.',vietnamese:'Băng qua đường cẩn thận.'},
{ id:'s915',category:'9',english:'Follow this road.',vietnamese:'Đi theo con đường này.'},
{ id:'s916',category:'9',english:'The car is very fast.',vietnamese:'Chiếc xe rất nhanh.'},
{ id:'s917',category:'9',english:'The bike is slow.',vietnamese:'Xe đạp chậm.'},
{ id:'s918',category:'9',english:'The station is far away.',vietnamese:'Nhà ga ở xa.'},
{ id:'s919',category:'9',english:'Please wait at the stop.',vietnamese:'Đợi ở trạm nhé.'},
{ id:'s920',category:'9',english:'The driver is friendly.',vietnamese:'Tài xế thân thiện.'},
{ id:'s921',category:'9',english:'The plane is boarding now.',vietnamese:'Máy bay đang lên khách.'},
{ id:'s922',category:'9',english:'We missed the train.',vietnamese:'Chúng tôi lỡ tàu rồi.'},
{ id:'s923',category:'9',english:'The road is closed.',vietnamese:'Đường bị đóng.'},
{ id:'s924',category:'9',english:'There is a traffic jam.',vietnamese:'Có kẹt xe.'},
{ id:'s925',category:'9',english:'Turn around here.',vietnamese:'Quay đầu ở đây.'},
{ id:'s926',category:'9',english:'The taxi is coming.',vietnamese:'Taxi sắp tới.'},
{ id:'s927',category:'9',english:'We are almost there.',vietnamese:'Sắp tới rồi.'},
{ id:'s928',category:'9',english:'The bus is full.',vietnamese:'Xe buýt đầy.'},
{ id:'s929',category:'9',english:'Please show me the way.',vietnamese:'Chỉ đường giúp tôi.'},
{ id:'s930',category:'9',english:'I am lost.',vietnamese:'Tôi bị lạc.'},

// Chủ đề Sức khỏe (ID: 10)
{ id:'s1001',category:'10',english:'I feel sick today.',vietnamese:'Hôm nay tôi thấy mệt.'},
{ id:'s1002',category:'10',english:'I have a fever.',vietnamese:'Tôi bị sốt.'},
{ id:'s1003',category:'10',english:'I have a bad headache.',vietnamese:'Tôi đau đầu dữ dội.'},
{ id:'s1004',category:'10',english:'My throat is sore.',vietnamese:'Tôi bị đau họng.'},
{ id:'s1005',category:'10',english:'I am coughing a lot.',vietnamese:'Tôi ho nhiều.'},
{ id:'s1006',category:'10',english:'My stomach hurts.',vietnamese:'Tôi đau bụng.'},
{ id:'s1007',category:'10',english:'I feel very tired.',vietnamese:'Tôi rất mệt.'},
{ id:'s1008',category:'10',english:'I need to see a doctor.',vietnamese:'Tôi cần đi gặp bác sĩ.'},
{ id:'s1009',category:'10',english:'The doctor gave me some medicine.',vietnamese:'Bác sĩ cho tôi thuốc.'},
{ id:'s1010',category:'10',english:'Please take this pill twice a day.',vietnamese:'Uống viên này ngày hai lần.'},
{ id:'s1011',category:'10',english:'I am feeling better now.',vietnamese:'Bây giờ tôi đỡ hơn.'},
{ id:'s1012',category:'10',english:'I am getting worse.',vietnamese:'Tôi đang tệ hơn.'},
{ id:'s1013',category:'10',english:'I need some rest.',vietnamese:'Tôi cần nghỉ ngơi.'},
{ id:'s1014',category:'10',english:'Please drink more water.',vietnamese:'Uống nhiều nước hơn.'},
{ id:'s1015',category:'10',english:'I went to the clinic.',vietnamese:'Tôi đi phòng khám.'},
{ id:'s1016',category:'10',english:'I have an allergy to seafood.',vietnamese:'Tôi dị ứng hải sản.'},
{ id:'s1017',category:'10',english:'He has a small injury.',vietnamese:'Anh ấy bị chấn thương nhẹ.'},
{ id:'s1018',category:'10',english:'My blood pressure is high.',vietnamese:'Huyết áp tôi cao.'},
{ id:'s1019',category:'10',english:'My temperature is normal.',vietnamese:'Nhiệt độ cơ thể bình thường.'},
{ id:'s1020',category:'10',english:'I am here for a check-up.',vietnamese:'Tôi đến khám tổng quát.'},
{ id:'s1021',category:'10',english:'The nurse will help you.',vietnamese:'Y tá sẽ giúp bạn.'},
{ id:'s1022',category:'10',english:'I need a prescription.',vietnamese:'Tôi cần đơn thuốc.'},
{ id:'s1023',category:'10',english:'The injection did not hurt much.',vietnamese:'Mũi tiêm không đau lắm.'},
{ id:'s1024',category:'10',english:'I need to recover quickly.',vietnamese:'Tôi cần hồi phục nhanh.'},
{ id:'s1025',category:'10',english:'Please rest at home.',vietnamese:'Nghỉ ở nhà nhé.'},
{ id:'s1026',category:'10',english:'I am healthy now.',vietnamese:'Bây giờ tôi khỏe rồi.'},
{ id:'s1027',category:'10',english:'Do you feel any pain?',vietnamese:'Bạn có thấy đau không?'},
{ id:'s1028',category:'10',english:'Where does it hurt?',vietnamese:'Bạn đau ở đâu?'},
{ id:'s1029',category:'10',english:'Please take care of yourself.',vietnamese:'Giữ gìn sức khỏe nhé.'},
{ id:'s1030',category:'10',english:'Call me if you feel worse.',vietnamese:'Gọi tôi nếu bạn thấy tệ hơn.'},

];