window.DATA_WORDS = [
  
// Chủ đề Gia đình (ID: 1)
{ id:'w1',category:'1',word:'Father',type:'Noun',meaning:'Bố',image:''},
{ id:'w2',category:'1',word:'Mother',type:'Noun',meaning:'Mẹ',image:''},
{ id:'w3',category:'1',word:'Parents',type:'Noun',meaning:'Bố mẹ',image:''},
{ id:'w4',category:'1',word:'Brother',type:'Noun',meaning:'Anh/em trai',image:''},
{ id:'w5',category:'1',word:'Sister',type:'Noun',meaning:'Chị/em gái',image:''},
{ id:'w6',category:'1',word:'Husband',type:'Noun',meaning:'Chồng',image:''},
{ id:'w7',category:'1',word:'Wife',type:'Noun',meaning:'Vợ',image:''},
{ id:'w8',category:'1',word:'Son',type:'Noun',meaning:'Con trai',image:''},
{ id:'w9',category:'1',word:'Daughter',type:'Noun',meaning:'Con gái',image:''},
{ id:'w10',category:'1',word:'Family',type:'Noun',meaning:'Gia đình',image:''},
{ id:'w11',category:'1',word:'Child',type:'Noun',meaning:'Con cái',image:''},
{ id:'w12',category:'1',word:'Kids',type:'Noun',meaning:'Bọn trẻ',image:''},
{ id:'w13',category:'1',word:'Married',type:'Adj',meaning:'Đã kết hôn',image:''},
{ id:'w14',category:'1',word:'Single',type:'Adj',meaning:'Độc thân',image:''},
{ id:'w15',category:'1',word:'Relatives',type:'Noun',meaning:'Họ hàng',image:''},
{ id:'w16',category:'1',word:'Baby',type:'Noun',meaning:'Em bé',image:''},
{ id:'w17',category:'1',word:'Home',type:'Noun',meaning:'Nhà',image:''},
{ id:'w18',category:'1',word:'Care',type:'Verb',meaning:'Chăm sóc',image:''},
{ id:'w19',category:'1',word:'Visit',type:'Verb',meaning:'Thăm',image:''},
{ id:'w20',category:'1',word:'Stay',type:'Verb',meaning:'Ở lại',image:''},
{ id:'w21',category:'1',word:'Help',type:'Verb',meaning:'Giúp',image:''},
{ id:'w22',category:'1',word:'Love',type:'Verb',meaning:'Yêu thương',image:''},
{ id:'w23',category:'1',word:'Together',type:'Adv',meaning:'Cùng nhau',image:''},
{ id:'w24',category:'1',word:'Support',type:'Verb',meaning:'Hỗ trợ',image:''},
{ id:'w25',category:'1',word:'Grow up',type:'Verb',meaning:'Lớn lên',image:''},
{ id:'w26',category:'1',word:'Take care of',type:'Verb',meaning:'Chăm sóc',image:''},
{ id:'w27',category:'1',word:'Spend time',type:'Verb',meaning:'Dành thời gian',image:''},
{ id:'w28',category:'1',word:'Live with',type:'Verb',meaning:'Sống cùng',image:''},
{ id:'w29',category:'1',word:'Close',type:'Adj',meaning:'Thân thiết',image:''},
{ id:'w30',category:'1',word:'Help each other',type:'Verb',meaning:'Giúp đỡ nhau',image:''},

// Chủ đề Bản thân (ID: 2)
{ id:'w1',category:'2',word:'Name',type:'Noun',meaning:'Tên',image:''},
{ id:'w2',category:'2',word:'Age',type:'Noun',meaning:'Tuổi',image:''},
{ id:'w3',category:'2',word:'From',type:'Prep',meaning:'Đến từ',image:''},
{ id:'w4',category:'2',word:'Live',type:'Verb',meaning:'Sống',image:''},
{ id:'w5',category:'2',word:'Work',type:'Verb',meaning:'Làm việc',image:''},
{ id:'w6',category:'2',word:'Job',type:'Noun',meaning:'Công việc',image:''},
{ id:'w7',category:'2',word:'City',type:'Noun',meaning:'Thành phố',image:''},
{ id:'w8',category:'2',word:'Country',type:'Noun',meaning:'Quốc gia',image:''},
{ id:'w9',category:'2',word:'Like',type:'Verb',meaning:'Thích',image:''},
{ id:'w10',category:'2',word:'Love',type:'Verb',meaning:'Rất thích',image:''},
{ id:'w11',category:'2',word:'Hobby',type:'Noun',meaning:'Sở thích',image:''},
{ id:'w12',category:'2',word:'Language',type:'Noun',meaning:'Ngôn ngữ',image:''},
{ id:'w13',category:'2',word:'English',type:'Noun',meaning:'Tiếng Anh',image:''},
{ id:'w14',category:'2',word:'Busy',type:'Adj',meaning:'Bận',image:''},
{ id:'w15',category:'2',word:'Free',type:'Adj',meaning:'Rảnh',image:''},
{ id:'w16',category:'2',word:'Tired',type:'Adj',meaning:'Mệt',image:''},
{ id:'w17',category:'2',word:'Happy',type:'Adj',meaning:'Vui',image:''},
{ id:'w18',category:'2',word:'Sad',type:'Adj',meaning:'Buồn',image:''},
{ id:'w19',category:'2',word:'Interested in',type:'Adj',meaning:'Quan tâm đến',image:''},
{ id:'w20',category:'2',word:'Learn',type:'Verb',meaning:'Học',image:''},
{ id:'w21',category:'2',word:'Speak',type:'Verb',meaning:'Nói',image:''},
{ id:'w22',category:'2',word:'Meet',type:'Verb',meaning:'Gặp',image:''},
{ id:'w23',category:'2',word:'Friend',type:'Noun',meaning:'Bạn',image:''},
{ id:'w24',category:'2',word:'People',type:'Noun',meaning:'Mọi người',image:''},
{ id:'w25',category:'2',word:'Now',type:'Adv',meaning:'Bây giờ',image:''},
{ id:'w26',category:'2',word:'Today',type:'Adv',meaning:'Hôm nay',image:''},
{ id:'w27',category:'2',word:'Here',type:'Adv',meaning:'Ở đây',image:''},
{ id:'w28',category:'2',word:'Every day',type:'Adv',meaning:'Mỗi ngày',image:''},
{ id:'w29',category:'2',word:'Online',type:'Adj',meaning:'Trực tuyến',image:''},
{ id:'w30',category:'2',word:'Home',type:'Noun',meaning:'Nhà',image:''},

  
// Chủ đề Số đếm & Thời gian (ID: 3)
{ id:'w1',category:'3',word:'One',type:'Number',meaning:'Một',image:''},
{ id:'w2',category:'3',word:'Two',type:'Number',meaning:'Hai',image:''},
{ id:'w3',category:'3',word:'Three',type:'Number',meaning:'Ba',image:''},
{ id:'w4',category:'3',word:'Morning',type:'Noun',meaning:'Buổi sáng',image:''},
{ id:'w5',category:'3',word:'Afternoon',type:'Noun',meaning:'Buổi chiều',image:''},
{ id:'w6',category:'3',word:'Evening',type:'Noun',meaning:'Buổi tối',image:''},
{ id:'w7',category:'3',word:'Night',type:'Noun',meaning:'Ban đêm',image:''},
{ id:'w8',category:'3',word:'Today',type:'Adv',meaning:'Hôm nay',image:''},
{ id:'w9',category:'3',word:'Tomorrow',type:'Adv',meaning:'Ngày mai',image:''},
{ id:'w10',category:'3',word:'Yesterday',type:'Adv',meaning:'Hôm qua',image:''},
{ id:'w11',category:'3',word:'Now',type:'Adv',meaning:'Bây giờ',image:''},
{ id:'w12',category:'3',word:'Later',type:'Adv',meaning:'Lát nữa',image:''},
{ id:'w13',category:'3',word:'Early',type:'Adj',meaning:'Sớm',image:''},
{ id:'w14',category:'3',word:'Late',type:'Adj',meaning:'Trễ',image:''},
{ id:'w15',category:'3',word:'Always',type:'Adv',meaning:'Luôn luôn',image:''},
{ id:'w16',category:'3',word:'Usually',type:'Adv',meaning:'Thường',image:''},
{ id:'w17',category:'3',word:'Sometimes',type:'Adv',meaning:'Thỉnh thoảng',image:''},
{ id:'w18',category:'3',word:'Never',type:'Adv',meaning:'Không bao giờ',image:''},
{ id:'w19',category:'3',word:'Week',type:'Noun',meaning:'Tuần',image:''},
{ id:'w20',category:'3',word:'Month',type:'Noun',meaning:'Tháng',image:''},
{ id:'w21',category:'3',word:'Year',type:'Noun',meaning:'Năm',image:''},
{ id:'w22',category:'3',word:'Minute',type:'Noun',meaning:'Phút',image:''},
{ id:'w23',category:'3',word:'Hour',type:'Noun',meaning:'Giờ',image:''},
{ id:'w24',category:'3',word:'Time',type:'Noun',meaning:'Thời gian',image:''},
{ id:'w25',category:'3',word:'On time',type:'Adj',meaning:'Đúng giờ',image:''},
{ id:'w26',category:'3',word:'Soon',type:'Adv',meaning:'Sắp',image:''},
{ id:'w27',category:'3',word:'All day',type:'Adv',meaning:'Cả ngày',image:''},
{ id:'w28',category:'3',word:'Every day',type:'Adv',meaning:'Mỗi ngày',image:''},
{ id:'w29',category:'3',word:'Right now',type:'Adv',meaning:'Ngay bây giờ',image:''},
{ id:'w30',category:'3',word:'Weekend',type:'Noun',meaning:'Cuối tuần',image:''},

// Chủ đề Màu sắc & Hình dạng (ID: 4)
{ id:'w401',category:'4',word:'Red',type:'Adj',meaning:'Đỏ',image:''},
{ id:'w402',category:'4',word:'Blue',type:'Adj',meaning:'Xanh dương',image:''},
{ id:'w403',category:'4',word:'Green',type:'Adj',meaning:'Xanh lá',image:''},
{ id:'w404',category:'4',word:'Yellow',type:'Adj',meaning:'Vàng',image:''},
{ id:'w405',category:'4',word:'Black',type:'Adj',meaning:'Đen',image:''},
{ id:'w406',category:'4',word:'White',type:'Adj',meaning:'Trắng',image:''},
{ id:'w407',category:'4',word:'Big',type:'Adj',meaning:'To',image:''},
{ id:'w408',category:'4',word:'Small',type:'Adj',meaning:'Nhỏ',image:''},
{ id:'w409',category:'4',word:'Long',type:'Adj',meaning:'Dài',image:''},
{ id:'w410',category:'4',word:'Short',type:'Adj',meaning:'Ngắn / thấp',image:''},
{ id:'w411',category:'4',word:'Round',type:'Adj',meaning:'Tròn',image:''},
{ id:'w412',category:'4',word:'Square',type:'Adj',meaning:'Vuông',image:''},
{ id:'w413',category:'4',word:'New',type:'Adj',meaning:'Mới',image:''},
{ id:'w414',category:'4',word:'Old',type:'Adj',meaning:'Cũ',image:''},
{ id:'w415',category:'4',word:'Light',type:'Adj',meaning:'Nhẹ / sáng',image:''},
{ id:'w416',category:'4',word:'Dark',type:'Adj',meaning:'Tối / đậm',image:''},
{ id:'w417',category:'4',word:'Clean',type:'Adj',meaning:'Sạch',image:''},
{ id:'w418',category:'4',word:'Dirty',type:'Adj',meaning:'Bẩn',image:''},
{ id:'w419',category:'4',word:'Hot',type:'Adj',meaning:'Nóng',image:''},
{ id:'w420',category:'4',word:'Cold',type:'Adj',meaning:'Lạnh',image:''},
{ id:'w421',category:'4',word:'Full',type:'Adj',meaning:'Đầy',image:''},
{ id:'w422',category:'4',word:'Empty',type:'Adj',meaning:'Trống',image:''},
{ id:'w423',category:'4',word:'Same',type:'Adj',meaning:'Giống nhau',image:''},
{ id:'w424',category:'4',word:'Different',type:'Adj',meaning:'Khác nhau',image:''},
{ id:'w425',category:'4',word:'Soft',type:'Adj',meaning:'Mềm',image:''},
{ id:'w426',category:'4',word:'Hard',type:'Adj',meaning:'Cứng',image:''},
{ id:'w427',category:'4',word:'Fast',type:'Adj',meaning:'Nhanh',image:''},
{ id:'w428',category:'4',word:'Slow',type:'Adj',meaning:'Chậm',image:''},
{ id:'w429',category:'4',word:'Near',type:'Adj',meaning:'Gần',image:''},
{ id:'w430',category:'4',word:'Far',type:'Adj',meaning:'Xa',image:''},

// Chủ đề Đồ vật xung quanh (ID: 5)
{ id:'w501',category:'5',word:'Table',type:'Noun',meaning:'Bàn',image:''},
{ id:'w502',category:'5',word:'Chair',type:'Noun',meaning:'Ghế',image:''},
{ id:'w503',category:'5',word:'Phone',type:'Noun',meaning:'Điện thoại',image:''},
{ id:'w504',category:'5',word:'Laptop',type:'Noun',meaning:'Máy tính xách tay',image:''},
{ id:'w505',category:'5',word:'TV',type:'Noun',meaning:'Tivi',image:''},
{ id:'w506',category:'5',word:'Remote',type:'Noun',meaning:'Điều khiển',image:''},
{ id:'w507',category:'5',word:'Fan',type:'Noun',meaning:'Quạt',image:''},
{ id:'w508',category:'5',word:'Light',type:'Noun',meaning:'Đèn',image:''},
{ id:'w509',category:'5',word:'Door',type:'Noun',meaning:'Cửa',image:''},
{ id:'w510',category:'5',word:'Window',type:'Noun',meaning:'Cửa sổ',image:''},
{ id:'w511',category:'5',word:'Key',type:'Noun',meaning:'Chìa khóa',image:''},
{ id:'w512',category:'5',word:'Bag',type:'Noun',meaning:'Túi',image:''},
{ id:'w513',category:'5',word:'Shoes',type:'Noun',meaning:'Giày',image:''},
{ id:'w514',category:'5',word:'Clothes',type:'Noun',meaning:'Quần áo',image:''},
{ id:'w515',category:'5',word:'Bottle',type:'Noun',meaning:'Chai',image:''},
{ id:'w516',category:'5',word:'Cup',type:'Noun',meaning:'Ly',image:''},
{ id:'w517',category:'5',word:'Plate',type:'Noun',meaning:'Đĩa',image:''},
{ id:'w518',category:'5',word:'Spoon',type:'Noun',meaning:'Muỗng',image:''},
{ id:'w519',category:'5',word:'Fork',type:'Noun',meaning:'Nĩa',image:''},
{ id:'w520',category:'5',word:'Book',type:'Noun',meaning:'Sách',image:''},
{ id:'w521',category:'5',word:'Pen',type:'Noun',meaning:'Bút',image:''},
{ id:'w522',category:'5',word:'Paper',type:'Noun',meaning:'Giấy',image:''},
{ id:'w523',category:'5',word:'Clock',type:'Noun',meaning:'Đồng hồ',image:''},
{ id:'w524',category:'5',word:'Mirror',type:'Noun',meaning:'Gương',image:''},
{ id:'w525',category:'5',word:'Towel',type:'Noun',meaning:'Khăn',image:''},
{ id:'w526',category:'5',word:'Soap',type:'Noun',meaning:'Xà phòng',image:''},
{ id:'w527',category:'5',word:'Trash',type:'Noun',meaning:'Rác',image:''},
{ id:'w528',category:'5',word:'Box',type:'Noun',meaning:'Hộp',image:''},
{ id:'w529',category:'5',word:'Shelf',type:'Noun',meaning:'Kệ',image:''},
{ id:'w530',category:'5',word:'Drawer',type:'Noun',meaning:'Ngăn kéo',image:''},

// Chủ đề Nhà cửa (ID: 6)
{ id:'w601',category:'6',word:'House',type:'Noun',meaning:'Nhà',image:''},
{ id:'w602',category:'6',word:'Room',type:'Noun',meaning:'Phòng',image:''},
{ id:'w603',category:'6',word:'Bedroom',type:'Noun',meaning:'Phòng ngủ',image:''},
{ id:'w604',category:'6',word:'Kitchen',type:'Noun',meaning:'Nhà bếp',image:''},
{ id:'w605',category:'6',word:'Bathroom',type:'Noun',meaning:'Phòng tắm',image:''},
{ id:'w606',category:'6',word:'Living room',type:'Noun',meaning:'Phòng khách',image:''},
{ id:'w607',category:'6',word:'Toilet',type:'Noun',meaning:'Nhà vệ sinh',image:''},
{ id:'w608',category:'6',word:'Bed',type:'Noun',meaning:'Giường',image:''},
{ id:'w609',category:'6',word:'Sofa',type:'Noun',meaning:'Ghế sofa',image:''},
{ id:'w610',category:'6',word:'Fridge',type:'Noun',meaning:'Tủ lạnh',image:''},
{ id:'w611',category:'6',word:'Stove',type:'Noun',meaning:'Bếp',image:''},
{ id:'w612',category:'6',word:'Sink',type:'Noun',meaning:'Bồn rửa',image:''},
{ id:'w613',category:'6',word:'Shower',type:'Noun',meaning:'Vòi sen',image:''},
{ id:'w614',category:'6',word:'Toilet paper',type:'Noun',meaning:'Giấy vệ sinh',image:''},
{ id:'w615',category:'6',word:'Pillow',type:'Noun',meaning:'Gối',image:''},
{ id:'w616',category:'6',word:'Blanket',type:'Noun',meaning:'Chăn',image:''},
{ id:'w617',category:'6',word:'Air conditioner',type:'Noun',meaning:'Máy lạnh',image:''},
{ id:'w618',category:'6',word:'Washing machine',type:'Noun',meaning:'Máy giặt',image:''},
{ id:'w619',category:'6',word:'Dryer',type:'Noun',meaning:'Máy sấy',image:''},
{ id:'w620',category:'6',word:'Fan',type:'Noun',meaning:'Quạt',image:''},
{ id:'w621',category:'6',word:'Lamp',type:'Noun',meaning:'Đèn',image:''},
{ id:'w622',category:'6',word:'Plug',type:'Noun',meaning:'Ổ cắm',image:''},
{ id:'w623',category:'6',word:'Switch',type:'Noun',meaning:'Công tắc',image:''},
{ id:'w624',category:'6',word:'Floor',type:'Noun',meaning:'Sàn',image:''},
{ id:'w625',category:'6',word:'Wall',type:'Noun',meaning:'Tường',image:''},
{ id:'w626',category:'6',word:'Ceiling',type:'Noun',meaning:'Trần nhà',image:''},
{ id:'w627',category:'6',word:'Curtain',type:'Noun',meaning:'Rèm',image:''},
{ id:'w628',category:'6',word:'Balcony',type:'Noun',meaning:'Ban công',image:''},
{ id:'w629',category:'6',word:'Garage',type:'Noun',meaning:'Nhà xe',image:''},
{ id:'w630',category:'6',word:'Yard',type:'Noun',meaning:'Sân',image:''},

// Chủ đề Thức ăn & Đồ uống (ID: 7)
{ id:'w701',category:'7',word:'Rice',type:'Noun',meaning:'Cơm',image:''},
{ id:'w702',category:'7',word:'Noodles',type:'Noun',meaning:'Mì',image:''},
{ id:'w703',category:'7',word:'Bread',type:'Noun',meaning:'Bánh mì',image:''},
{ id:'w704',category:'7',word:'Chicken',type:'Noun',meaning:'Gà',image:''},
{ id:'w705',category:'7',word:'Beef',type:'Noun',meaning:'Bò',image:''},
{ id:'w706',category:'7',word:'Pork',type:'Noun',meaning:'Heo',image:''},
{ id:'w707',category:'7',word:'Fish',type:'Noun',meaning:'Cá',image:''},
{ id:'w708',category:'7',word:'Egg',type:'Noun',meaning:'Trứng',image:''},
{ id:'w709',category:'7',word:'Soup',type:'Noun',meaning:'Canh/súp',image:''},
{ id:'w710',category:'7',word:'Salad',type:'Noun',meaning:'Salad',image:''},
{ id:'w711',category:'7',word:'Fruit',type:'Noun',meaning:'Trái cây',image:''},
{ id:'w712',category:'7',word:'Vegetable',type:'Noun',meaning:'Rau',image:''},
{ id:'w713',category:'7',word:'Apple',type:'Noun',meaning:'Táo',image:''},
{ id:'w714',category:'7',word:'Banana',type:'Noun',meaning:'Chuối',image:''},
{ id:'w715',category:'7',word:'Orange',type:'Noun',meaning:'Cam',image:''},
{ id:'w716',category:'7',word:'Water',type:'Noun',meaning:'Nước',image:''},
{ id:'w717',category:'7',word:'Tea',type:'Noun',meaning:'Trà',image:''},
{ id:'w718',category:'7',word:'Coffee',type:'Noun',meaning:'Cà phê',image:''},
{ id:'w719',category:'7',word:'Milk',type:'Noun',meaning:'Sữa',image:''},
{ id:'w720',category:'7',word:'Juice',type:'Noun',meaning:'Nước ép',image:''},
{ id:'w721',category:'7',word:'Delicious',type:'Adj',meaning:'Ngon',image:''},
{ id:'w722',category:'7',word:'Sweet',type:'Adj',meaning:'Ngọt',image:''},
{ id:'w723',category:'7',word:'Salty',type:'Adj',meaning:'Mặn',image:''},
{ id:'w724',category:'7',word:'Spicy',type:'Adj',meaning:'Cay',image:''},
{ id:'w725',category:'7',word:'Hot',type:'Adj',meaning:'Nóng',image:''},
{ id:'w726',category:'7',word:'Cold',type:'Adj',meaning:'Lạnh',image:''},
{ id:'w727',category:'7',word:'Hungry',type:'Adj',meaning:'Đói',image:''},
{ id:'w728',category:'7',word:'Full',type:'Adj',meaning:'No',image:''},
{ id:'w729',category:'7',word:'Order',type:'Verb',meaning:'Gọi món',image:''},
{ id:'w730',category:'7',word:'Eat',type:'Verb',meaning:'Ăn',image:''},

// Chủ đề Mua sắm (ID: 8)
{ id:'w801',category:'8',word:'Shop',type:'Noun',meaning:'Cửa hàng',image:''},
{ id:'w802',category:'8',word:'Store',type:'Noun',meaning:'Cửa tiệm',image:''},
{ id:'w803',category:'8',word:'Market',type:'Noun',meaning:'Chợ',image:''},
{ id:'w804',category:'8',word:'Price',type:'Noun',meaning:'Giá',image:''},
{ id:'w805',category:'8',word:'Cheap',type:'Adj',meaning:'Rẻ',image:''},
{ id:'w806',category:'8',word:'Expensive',type:'Adj',meaning:'Đắt',image:''},
{ id:'w807',category:'8',word:'Buy',type:'Verb',meaning:'Mua',image:''},
{ id:'w808',category:'8',word:'Sell',type:'Verb',meaning:'Bán',image:''},
{ id:'w809',category:'8',word:'Pay',type:'Verb',meaning:'Trả tiền',image:''},
{ id:'w810',category:'8',word:'Cash',type:'Noun',meaning:'Tiền mặt',image:''},
{ id:'w811',category:'8',word:'Card',type:'Noun',meaning:'Thẻ',image:''},
{ id:'w812',category:'8',word:'Receipt',type:'Noun',meaning:'Hóa đơn',image:''},
{ id:'w813',category:'8',word:'Discount',type:'Noun',meaning:'Giảm giá',image:''},
{ id:'w814',category:'8',word:'Sale',type:'Noun',meaning:'Khuyến mãi',image:''},
{ id:'w815',category:'8',word:'Change',type:'Noun',meaning:'Tiền thối',image:''},
{ id:'w816',category:'8',word:'Size',type:'Noun',meaning:'Kích cỡ',image:''},
{ id:'w817',category:'8',word:'Try on',type:'Verb',meaning:'Thử đồ',image:''},
{ id:'w818',category:'8',word:'Fit',type:'Verb',meaning:'Vừa',image:''},
{ id:'w819',category:'8',word:'Color',type:'Noun',meaning:'Màu',image:''},
{ id:'w820',category:'8',word:'Quality',type:'Noun',meaning:'Chất lượng',image:''},
{ id:'w821',category:'8',word:'Return',type:'Verb',meaning:'Trả hàng',image:''},
{ id:'w822',category:'8',word:'Refund',type:'Noun',meaning:'Hoàn tiền',image:''},
{ id:'w823',category:'8',word:'Order',type:'Verb',meaning:'Đặt hàng',image:''},
{ id:'w824',category:'8',word:'Delivery',type:'Noun',meaning:'Giao hàng',image:''},
{ id:'w825',category:'8',word:'Online',type:'Adj',meaning:'Trực tuyến',image:''},
{ id:'w826',category:'8',word:'Customer',type:'Noun',meaning:'Khách hàng',image:''},
{ id:'w827',category:'8',word:'Seller',type:'Noun',meaning:'Người bán',image:''},
{ id:'w828',category:'8',word:'Product',type:'Noun',meaning:'Sản phẩm',image:''},
{ id:'w829',category:'8',word:'Brand',type:'Noun',meaning:'Thương hiệu',image:''},
{ id:'w830',category:'8',word:'Bag',type:'Noun',meaning:'Túi mua hàng',image:''},

// Chủ đề Giao thông (ID: 9)
{ id:'w901',category:'9',word:'Road',type:'Noun',meaning:'Đường',image:''},
{ id:'w902',category:'9',word:'Street',type:'Noun',meaning:'Phố',image:''},
{ id:'w903',category:'9',word:'Bus',type:'Noun',meaning:'Xe buýt',image:''},
{ id:'w904',category:'9',word:'Taxi',type:'Noun',meaning:'Taxi',image:''},
{ id:'w905',category:'9',word:'Train',type:'Noun',meaning:'Tàu hỏa',image:''},
{ id:'w906',category:'9',word:'Plane',type:'Noun',meaning:'Máy bay',image:''},
{ id:'w907',category:'9',word:'Bike',type:'Noun',meaning:'Xe đạp',image:''},
{ id:'w908',category:'9',word:'Motorbike',type:'Noun',meaning:'Xe máy',image:''},
{ id:'w909',category:'9',word:'Car',type:'Noun',meaning:'Ô tô',image:''},
{ id:'w910',category:'9',word:'Driver',type:'Noun',meaning:'Tài xế',image:''},
{ id:'w911',category:'9',word:'Stop',type:'Noun',meaning:'Trạm dừng',image:''},
{ id:'w912',category:'9',word:'Station',type:'Noun',meaning:'Nhà ga',image:''},
{ id:'w913',category:'9',word:'Airport',type:'Noun',meaning:'Sân bay',image:''},
{ id:'w914',category:'9',word:'Ticket',type:'Noun',meaning:'Vé',image:''},
{ id:'w915',category:'9',word:'Map',type:'Noun',meaning:'Bản đồ',image:''},
{ id:'w916',category:'9',word:'Direction',type:'Noun',meaning:'Hướng',image:''},
{ id:'w917',category:'9',word:'Left',type:'Adj',meaning:'Trái',image:''},
{ id:'w918',category:'9',word:'Right',type:'Adj',meaning:'Phải',image:''},
{ id:'w919',category:'9',word:'Straight',type:'Adv',meaning:'Thẳng',image:''},
{ id:'w920',category:'9',word:'Near',type:'Adj',meaning:'Gần',image:''},
{ id:'w921',category:'9',word:'Far',type:'Adj',meaning:'Xa',image:''},
{ id:'w922',category:'9',word:'Traffic',type:'Noun',meaning:'Giao thông',image:''},
{ id:'w923',category:'9',word:'Jam',type:'Noun',meaning:'Kẹt xe',image:''},
{ id:'w924',category:'9',word:'Cross',type:'Verb',meaning:'Băng qua',image:''},
{ id:'w925',category:'9',word:'Turn',type:'Verb',meaning:'Rẽ',image:''},
{ id:'w926',category:'9',word:'Follow',type:'Verb',meaning:'Đi theo',image:''},
{ id:'w927',category:'9',word:'Arrive',type:'Verb',meaning:'Đến nơi',image:''},
{ id:'w928',category:'9',word:'Leave',type:'Verb',meaning:'Rời đi',image:''},
{ id:'w929',category:'9',word:'Fast',type:'Adj',meaning:'Nhanh',image:''},
{ id:'w930',category:'9',word:'Slow',type:'Adj',meaning:'Chậm',image:''},

// Chủ đề Sức khỏe (ID: 10)
{ id:'w1001',category:'10',word:'Doctor',type:'Noun',meaning:'Bác sĩ',image:''},
{ id:'w1002',category:'10',word:'Nurse',type:'Noun',meaning:'Y tá',image:''},
{ id:'w1003',category:'10',word:'Hospital',type:'Noun',meaning:'Bệnh viện',image:''},
{ id:'w1004',category:'10',word:'Clinic',type:'Noun',meaning:'Phòng khám',image:''},
{ id:'w1005',category:'10',word:'Medicine',type:'Noun',meaning:'Thuốc',image:''},
{ id:'w1006',category:'10',word:'Pain',type:'Noun',meaning:'Đau',image:''},
{ id:'w1007',category:'10',word:'Fever',type:'Noun',meaning:'Sốt',image:''},
{ id:'w1008',category:'10',word:'Cough',type:'Noun',meaning:'Ho',image:''},
{ id:'w1009',category:'10',word:'Cold',type:'Noun',meaning:'Cảm lạnh',image:''},
{ id:'w1010',category:'10',word:'Flu',type:'Noun',meaning:'Cúm',image:''},
{ id:'w1011',category:'10',word:'Headache',type:'Noun',meaning:'Đau đầu',image:''},
{ id:'w1012',category:'10',word:'Stomachache',type:'Noun',meaning:'Đau bụng',image:''},
{ id:'w1013',category:'10',word:'Sore throat',type:'Noun',meaning:'Đau họng',image:''},
{ id:'w1014',category:'10',word:'Runny nose',type:'Noun',meaning:'Sổ mũi',image:''},
{ id:'w1015',category:'10',word:'Tired',type:'Adj',meaning:'Mệt',image:''},
{ id:'w1016',category:'10',word:'Weak',type:'Adj',meaning:'Yếu',image:''},
{ id:'w1017',category:'10',word:'Better',type:'Adj',meaning:'Đỡ hơn',image:''},
{ id:'w1018',category:'10',word:'Worse',type:'Adj',meaning:'Tệ hơn',image:''},
{ id:'w1019',category:'10',word:'Healthy',type:'Adj',meaning:'Khỏe mạnh',image:''},
{ id:'w1020',category:'10',word:'Sick',type:'Adj',meaning:'Ốm',image:''},
{ id:'w1021',category:'10',word:'Allergy',type:'Noun',meaning:'Dị ứng',image:''},
{ id:'w1022',category:'10',word:'Injury',type:'Noun',meaning:'Chấn thương',image:''},
{ id:'w1023',category:'10',word:'Blood pressure',type:'Noun',meaning:'Huyết áp',image:''},
{ id:'w1024',category:'10',word:'Temperature',type:'Noun',meaning:'Nhiệt độ cơ thể',image:''},
{ id:'w1025',category:'10',word:'Check-up',type:'Noun',meaning:'Khám tổng quát',image:''},
{ id:'w1026',category:'10',word:'Prescription',type:'Noun',meaning:'Đơn thuốc',image:''},
{ id:'w1027',category:'10',word:'Pill',type:'Noun',meaning:'Viên thuốc',image:''},
{ id:'w1028',category:'10',word:'Injection',type:'Noun',meaning:'Mũi tiêm',image:''},
{ id:'w1029',category:'10',word:'Rest',type:'Verb',meaning:'Nghỉ ngơi',image:''},
{ id:'w1030',category:'10',word:'Recover',type:'Verb',meaning:'Hồi phục',image:''},

];